fix: update Discord ID regex to include 19 digit IDs
sct/overseerr pull request #2860
Opened 2022-07-14 23:52 UTC by frank-cywong

#### Description
From July 22 onwards, new Discord accounts will have 19 digit Discord IDs (https://snowsta.mp/?l=en-us&z=6&f=atx10uuark-7ps), this is similar to #971 in terms of how it changes the regex.

#### Screenshot (if UI-related)
NA

#### To-Dos
NA

#### Issues Fixed or Closed
No such issue reported yet as the bug could only occur after July 22 at the earliest

2022-07-15 00:31 UTC, TheCatLady requested changes
Please test your changes next time. 😉

2022-07-15 00:31 UTC, TheCatLady commented on src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
> +      .matches(/^\d{17,18,19}$/, intl.formatMessage(messages.validationDiscordId)),
```suggestion
      .matches(/^\d{17,19}$/, intl.formatMessage(messages.validationDiscordId)),
```

2022-07-15 00:31 UTC, TheCatLady commented on src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsDiscord.tsx
> +      .matches(/^\d{17,18,19}$/, intl.formatMessage(messages.validationDiscordId)),
```suggestion
      .matches(/^\d{17,19}$/, intl.formatMessage(messages.validationDiscordId)),
```

2022-07-15 01:01 UTC, frank-cywong commented
Right, thanks for the heads up, probably shouldn't have deleted the entire todo list part of the PR

2022-08-03 00:40 UTC, sct approved these changes

2022-08-03 01:24 UTC, merged

2022-08-03 01:25 UTC, sct commented
Thanks for fixing it up!

2022-08-03 01:25 UTC, sct commented
@all-contributors please add @frank-cywong for code