feat(settings): basic log api and ui
sct/overseerr pull request #337
Opened 2020-12-16 03:00 UTC by lochstar

#### Description

This implements a very basic log UI. The number of rows returned is set to 1000. I thought I'd get this in so others can pick up from it and we can decide what we'd like from the log ui.

I separated the winston transport configs to use a JSON format for the file log, using the current text-based log that we output to the console wasn't compatible with `winston.query`. We should probably set some [options related to maximum files and filesize](https://github.com/winstonjs/winston/blob/2625f60c5c85b8c4926c65e98a591f8b42e0db9a/docs/transports.md#file-transport).

Other features we could implement:

- Filters e.g. by label/level
- Download link/view raw
- Nicer styling
- Manual/auto refresh option

#### Screenshot (if UI related)

![image](https://i.imgur.com/oWDC1xm.png)

#### Issues Fixed or Closed by this PR

- Fixes #272

2020-12-16 05:18 UTC, sct commented
I converted this to a draft for now while we get it ironed out.

2020-12-17 14:01 UTC, sct requested changes

2020-12-17 14:01 UTC, sct commented on src/components/Settings/SettingsLogs/index.tsx
> +    'You can access your logs directly in stdout (container logs) or looking in /app/config/logs/overseerr.logs',
We will want to have the same `<code>` tags in here like we did in the temporary message. If you only put the tags in here by themselves though, they will be just rendered out in the string.

You can see how this is done in the `RequestList` component. I apply <strong> tags in there.

2020-12-17 14:01 UTC, sct commented on src/components/Settings/SettingsLogs/index.tsx
> +        </div>
We can maybe re-use the table component here to make this look nice? Check out how i use it in the RequestList component.

2020-12-21 12:17 UTC, sct commented
@lochstar Are you still working on this?

2020-12-21 21:11 UTC, lochstar commented
Planning on it, yes.

2021-01-25 02:14 UTC, closed without merging